### ISSUE TITLE
Didn't discover the instance storage correctly for i3.xlarge aws instance

### ISSUE THREAD

**Issue by briankmatheson** [mayadata-io/mayastor-terraform-playground#2]
Didn't discover the instance storage correctly though:
bmath@timesink:~/maya/tf/test410$ kubectl logs -n kube-system system-setup-4nk9x  init-node 
NAME    MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0     7:0    0  28.1M  1 loop /snap/amazon-ssm-agent/2333
loop1     7:1    0  55.4M  1 loop /snap/core18/1932
loop2     7:2    0  67.8M  1 loop /snap/lxd/18150
loop3     7:3    0    31M  1 loop /snap/snapd/9721
xvda    202:0    0     8G  0 disk 
└─xvda1 202:1    0     8G  0 part /
xvdh    202:112  0     5G  0 disk 
nvme0n1 259:0    0 884.8G  0 disk 

Brian Matheson:speech_balloon:  < 1 minute ago
but
Spec:
  Disks:
    /dev/nvme1n1
  Node:  worker-0

**Comment by kellyhair** [comment]
From @arne-rusek: 

it's hardcoded here: I'll pull it to variable at least and give some comments around instance types so user knows to tweak it https://github.com/mayadata-io/mayastor-terraform-playground/blob/main/aws-kubeadm/main.tf#L41 (not sure how much of a terraformer you are, so maybe stating the obvious, but changing it and doing terraform apply should work as well - TF should figure out what needs to be done to make it happen); I'll make a note about discovery to my todo. Thanks for trying 

aws-kubeadm/main.tf:41
  mayastor_disk     = "/dev/nvme1n1"

**Comment by arne-rusek** [comment]
For those feeling adventurous, until implemented:

Edit `modules/k8s/variables.tf` - search for worker_instance_type and you also have to edit in ./main.tf hardcoded mayastor_disk and put there the name under which the disk will appear -- worker will still get the EBS test volume, but should use yours configured one... (untested :slightly_smiling_face:)

**Comment by arne-rusek** [comment]
To anyone interested, for `i3.xlarge` check out [i3](https://github.com/mayadata-io/mayastor-terraform-playground/tree/i3) branch

**Comment by briankmatheson** [comment]
cool, yes it's pretty roomy for the price.

BTW, how do you kill it dead?  bin/destroy-quick.

**Comment by bobek** [comment]
> BTW, how do you kill it dead? `bin/destroy-quick`.

Yes, it should also work on AWS. It skips some of the terraform dance, so it is quick (hence the name). You can also use `terraform destroy` which is the standard way. But it typically takes significantly longer.

**Comment by arne-rusek** [comment]
> > BTW, how do you kill it dead? `bin/destroy-quick`.
> 
> Yes, it should also work on AWS. It skips some of the terraform dance, so it is quick (hence the name). You can also use `terraform destroy` which is the standard way. But it typically takes significantly longer.

In rare cases one can deploy resources that would block destruction of tf deployed part and destroy might block (I know that https://kubedb.com/ does that). Script should avoid that too.

**Comment by arne-rusek** [comment]
Created PR (draft for now) to support multiple different instances nicely. https://github.com/mayadata-io/mayastor-terraform-playground/pull/13
