### ISSUE TITLE
Add support for creating an AWS cluster with multiple worker node types

### ISSUE THREAD

**Issue by watcher00090** [mayadata-io/mayastor-terraform-playground#24]
We'll need to be able to create an AWS cluster with at least 3 different worker node types, each passed in from the command line. We'll need one node type for storage servers, one for hosting apps that are either stateless or only mounting Mayastor volumes, and one for stuff we don't know about yet (likely small nodes that have instance storage for use with localpv)

**Comment by arne-rusek** [comment]
FYI: Terraform supports passing variables via file, environment variables or command line. https://www.terraform.io/docs/language/values/variables.html#assigning-values-to-root-module-variables

**Comment by watcher00090** [comment]
We'd like to create an AWS cluster that has many types of worker nodes present simultaneously. We'd like to input to Terraform something like [{type = "i3.large", count = 4, storage = "10GB"}, {type = "c4.medium", count = 2}, {type = "m5d.metal", count = 2, storage_server = true}] to configure how many workers of each type get created. The "storage_server = true" flag will have mayastor run on that node. The mayastor pods will only run on the storage server nodes.

**Comment by watcher00090** [comment]
https://mayadata.atlassian.net/browse/CAS-666
